### Base URL
@baseUrl = http://localhost:5000/api/dashboard

### Token (Analyst / Admin REQUIRED)
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5ZDA5OTZkODIwNGU4MzE2ZTNkNzc2YiIsImlhdCI6MTc3NTI3OTIzMSwiZXhwIjoxNzc1ODg0MDMxfQ.fG6Q-8guQ5T9lCkwOn72Hr4Gbbw3BXB51Jm1QrqS0zQ


### =========================
### 1. Overview (Income / Expense / Balance)
### =========================
GET {{baseUrl}}/overview
Authorization: Bearer {{token}}


### =========================
### 2. Category Breakdown
### =========================
GET {{baseUrl}}/categories
Authorization: Bearer {{token}}


### =========================
### 3. Monthly Trends (Year Wise)
### =========================
GET {{baseUrl}}/monthly?year=2024
Authorization: Bearer {{token}}


### =========================
### 4. Recent Transactions
### =========================
GET {{baseUrl}}/recent?limit=10
Authorization: Bearer {{token}}


### =========================
### 5. Weekly Trends
### =========================
GET {{baseUrl}}/weekly?weeks=4
Authorization: Bearer {{token}}